"""
claim_classifier.py

Purpose:
---------
Classifies a claim generated by Gemini.

Classification Types:
---------------------

EXECUTABLE_CLAIM
    The claim already exists in the
    executable_claims collection and can
    be evaluated by the Assurance Engine.

POTENTIAL_ASSURANCE_GAP
    The claim does not currently exist in
    executable_claims and therefore requires
    human review and possible claim creation.

Author:
-------
Indranil Jaiswal
AI Assurance Platform
"""

from pymongo import MongoClient
from dotenv import load_dotenv
import os

# --------------------------------------------------
# Load configuration
# --------------------------------------------------

load_dotenv()

mongodb_uri = os.getenv("MONGODB_URI")

if not mongodb_uri:
    raise ValueError(
        "MONGODB_URI not configured"
    )

# --------------------------------------------------
# MongoDB connection
# --------------------------------------------------

client = MongoClient(mongodb_uri)

db = client["ai_assurance"]

executable_claims = db["executable_claims"]


class ClaimClassifier:

    def classify(self, claim_name: str) -> dict:
        """
        Determine whether a claim can
        currently be executed by the
        Assurance Engine.
        """

        existing_claim = executable_claims.find_one(
            {"claim_name": claim_name}
        )

        if existing_claim:

            return {
                "claim_name": claim_name,
                "classification": "EXECUTABLE_CLAIM"
            }

        return {
            "claim_name": claim_name,
            "classification": "POTENTIAL_ASSURANCE_GAP"
        }
