"""
Claim Approval Engine

Purpose:
Convert claim suggestions into approved claim IDs.

Important:
This module represents human governance.

In Phase 2B, approval is simulated using a list of selected claim IDs.
Later, the dashboard will provide checkboxes for approval.
"""


class ClaimApprovalEngine:
    """
    Converts suggested claims into approved claims.
    """

    def approve_claims(
        self,
        suggestions,
        approved_claim_ids: list[str],
    ):
        """
        Approve selected claims.

        Parameters
        ----------
        suggestions:
            Claim suggestions generated by a policy or standards agent.

        approved_claim_ids:
            Claim IDs selected by the human reviewer.
        """

        approved = []

        for suggestion in suggestions:

            if suggestion.claim_id in approved_claim_ids:

                suggestion.approved = True
                approved.append(suggestion)

        return approved
